# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultinhome',
            name='children_details',
            field=models.TextField(default='', null=True),
        ),
    ]
