# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_month',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='move_in_year',
        ),
    ]
