# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminalrecordcheck',
            name='send_certificate_declare',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='security_question',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sms_resend_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sms_resend_attempts_expiry_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
    ]
