# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
