# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_applicantname_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
