# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_auto_20190311_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationReference',
        ),
        migrations.AddField(
            model_name='previousname',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
