# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0003_auto_20190912_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultinhome',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicantname',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='other_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
