# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0004_auto_20180522_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheckCurrent',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'CURRENT_ILLNESS',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckHospital',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'HOSPITAL_ADMISSION',
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCheckSerious',
            fields=[
                ('illness_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'SERIOUS_ILLNESS',
                'ordering': ['start_date'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='permission_declare',
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='current_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='email_resent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='email_resent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='health_check_status',
            field=models.CharField(default='To do', max_length=50),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='hospital_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='serious_illness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arc',
            name='childcare_type_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='dbs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='first_aid_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='health_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='login_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='people_in_home_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='personal_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='references_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AddField(
            model_name='healthcheckserious',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.AdultInHome'),
        ),
        migrations.AddField(
            model_name='healthcheckhospital',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.AdultInHome'),
        ),
        migrations.AddField(
            model_name='healthcheckcurrent',
            name='person_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.AdultInHome'),
        ),
    ]
