# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0005_auto_20180522_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckcurrent',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='healthcheckhospital',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='healthcheckserious',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='current_treatment',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='email_resent',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='email_resent_timestamp',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='health_check_status',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='hospital_admission',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='serious_illness',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='token',
        ),
        migrations.RemoveField(
            model_name='adultinhome',
            name='validated',
        ),
        migrations.AddField(
            model_name='adultinhome',
            name='permission_declare',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='arc',
            name='childcare_type_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='dbs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='eyfs_review',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='first_aid_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='health_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='login_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='people_in_home_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='personal_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='arc',
            name='references_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETED', 'COMPLETED')], max_length=50),
        ),
        migrations.DeleteModel(
            name='HealthCheckCurrent',
        ),
        migrations.DeleteModel(
            name='HealthCheckHospital',
        ),
        migrations.DeleteModel(
            name='HealthCheckSerious',
        ),
    ]
