# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 16:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0006_auto_20180523_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adultinhome',
            name='permission_declare',
        ),
        migrations.RemoveField(
            model_name='application',
            name='order_code',
        ),
        migrations.AddField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('(\\w{2})([0-9]{7})')]),
        ),
    ]
