# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArcReview',
        ),
    ]
