from .contact_details import contact_summary
from .review import PreviousRegistrationDetailsView, OtherPersonPreviousRegistrationDetailsView
from .type_of_childcare import type_of_childcare_age_groups