# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultInHome',
            fields=[
                ('adult_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('relationship', models.CharField(max_length=100)),
                ('dbs_certificate_number', models.CharField(max_length=50)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('permission_declare', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'ADULT_IN_HOME',
            },
        ),
        migrations.CreateModel(
            name='ApplicantHomeAddress',
            fields=[
                ('home_address_id', models.UUIDField(primary_key=True, serialize=False)),
                ('street_line1', models.CharField(max_length=100)),
                ('street_line2', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('childcare_address', models.NullBooleanField()),
                ('current_address', models.NullBooleanField()),
                ('move_in_month', models.IntegerField()),
                ('move_in_year', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'APPLICANT_HOME_ADDRESS',
            },
        ),
        migrations.CreateModel(
            name='ApplicantName',
            fields=[
                ('name_id', models.UUIDField(primary_key=True, serialize=False)),
                ('current_name', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'APPLICANT_NAME',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPersonalDetails',
            fields=[
                ('personal_detail_id', models.UUIDField(primary_key=True, serialize=False)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'APPLICANT_PERSONAL_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(primary_key=True, serialize=False)),
                ('application_type', models.CharField(max_length=50)),
                ('application_status', models.CharField(max_length=50)),
                ('cygnum_urn', models.CharField(max_length=50)),
                ('login_details_status', models.CharField(max_length=50)),
                ('personal_details_status', models.CharField(max_length=50)),
                ('childcare_type_status', models.CharField(max_length=50)),
                ('first_aid_training_status', models.CharField(max_length=50)),
                ('eyfs_training_status', models.CharField(max_length=50)),
                ('criminal_record_check_status', models.CharField(max_length=50)),
                ('health_status', models.CharField(max_length=50)),
                ('references_status', models.CharField(max_length=50)),
                ('people_in_home_status', models.CharField(max_length=50)),
                ('declarations_status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('order_code', models.UUIDField(blank=True, null=True)),
                ('adults_in_home', models.NullBooleanField()),
                ('children_in_home', models.NullBooleanField()),
                ('children_turning_16', models.NullBooleanField()),
                ('background_check_declare', models.NullBooleanField()),
                ('eyfs_questions_declare', models.NullBooleanField()),
                ('inspect_home_declare', models.NullBooleanField()),
                ('interview_declare', models.NullBooleanField()),
                ('information_correct_declare', models.NullBooleanField()),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'APPLICATION',
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='ChildcareType',
            fields=[
                ('childcare_id', models.UUIDField(primary_key=True, serialize=False)),
                ('zero_to_five', models.BooleanField()),
                ('five_to_eight', models.BooleanField()),
                ('eight_plus', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'CHILDCARE_TYPE',
            },
        ),
        migrations.CreateModel(
            name='ChildInHome',
            fields=[
                ('child_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('relationship', models.CharField(max_length=100)),
                ('child', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CHILD_IN_HOME',
            },
        ),
        migrations.CreateModel(
            name='CriminalRecordCheck',
            fields=[
                ('criminal_record_id', models.UUIDField(primary_key=True, serialize=False)),
                ('dbs_certificate_number', models.CharField(max_length=50)),
                ('cautions_convictions', models.BooleanField()),
                ('send_certificate_declare', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'CRIMINAL_RECORD_CHECK',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Eyfs',
            fields=[
                ('eyfs_id', models.UUIDField(primary_key=True, serialize=False)),
                ('eyfs_understand', models.NullBooleanField()),
                ('eyfs_training_declare', models.NullBooleanField()),
                ('eyfs_questions_declare', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'EYFS',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTraining',
            fields=[
                ('first_aid_id', models.UUIDField(primary_key=True, serialize=False)),
                ('training_organisation', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('course_day', models.IntegerField()),
                ('course_month', models.IntegerField()),
                ('course_year', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'FIRST_AID_TRAINING',
            },
        ),
        migrations.CreateModel(
            name='GovukTemplateBaseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('localise_name', models.BooleanField()),
                ('link', models.CharField(max_length=255)),
                ('link_is_view_name', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'govuk_template_base_link',
            },
        ),
        migrations.CreateModel(
            name='GovukTemplateBaseServicesettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('localise_name', models.BooleanField()),
                ('phase', models.CharField(max_length=10)),
                ('header_link_view_name', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'govuk_template_base_servicesettings',
            },
        ),
        migrations.CreateModel(
            name='GovukTemplateBaseServicesettingsFooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'govuk_template_base_servicesettings_footer_links',
            },
        ),
        migrations.CreateModel(
            name='GovukTemplateBaseServicesettingsHeaderLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'govuk_template_base_servicesettings_header_links',
            },
        ),
        migrations.CreateModel(
            name='Hdb',
            fields=[
                ('hdb_id', models.UUIDField(primary_key=True, serialize=False)),
                ('send_hdb_declare', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'HDB',
            },
        ),
        migrations.CreateModel(
            name='HealthDeclarationBooklet',
            fields=[
                ('hdb_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('send_hdb_declare', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'HDB',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('reference_id', models.UUIDField(primary_key=True, serialize=False)),
                ('reference', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('years_known', models.IntegerField()),
                ('months_known', models.IntegerField()),
                ('street_line1', models.CharField(max_length=100)),
                ('street_line2', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'REFERENCE',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('login_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('add_phone_number', models.CharField(max_length=20)),
                ('email_expiry_date', models.IntegerField(blank=True, null=True)),
                ('sms_expiry_date', models.IntegerField(blank=True, null=True)),
                ('magic_link_email', models.CharField(blank=True, max_length=100, null=True)),
                ('magic_link_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('security_question', models.CharField(blank=True, max_length=100, null=True)),
                ('security_answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'USER_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='ArcReview',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('last_accessed', models.CharField(max_length=50)),
                ('app_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ARC_REVIEW',
            },
        ),
        migrations.CreateModel(
            name='ArcStatus',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
