# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousName',
            fields=[
                ('previous_name_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('other_person_type', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_names', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('adult_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.AdultInHome')),
                ('child_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.ChildInHome')),
            ],
            options={
                'db_table': 'PREVIOUS_NAME',
            },
        ),
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='adult_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.AdultInHome'),
        ),
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='child_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arc_application.ChildInHome'),
        ),
    ]
