# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
