# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousAddress',
            fields=[
                ('previous_name_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField(blank=True)),
                ('person_type', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], max_length=50)),
                ('street_line1', models.CharField(blank=True, max_length=100)),
                ('street_line2', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'db_table': 'PREVIOUS_ADDRESS',
            },
        ),
        migrations.CreateModel(
            name='PreviousName',
            fields=[
                ('previous_name_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('person_id', models.UUIDField(blank=True)),
                ('other_person_type', models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_names', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'PREVIOUS_NAME',
            },
        ),
    ]
