# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcstatus',
            name='childcare_type_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='dbs_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='declaration_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='first_aid_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='health_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='login_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='people_in_home_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='personal_details_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arcstatus',
            name='references_review',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('FLAGGED', 'FLAGGED'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='arcstatus',
            table='ARC_STATUS',
        ),
    ]
