# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_auto_20180425_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousRegistrationDetails',
            fields=[
                ('personal_detail_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('previous_registration', models.NullBooleanField(default=False)),
                ('five_years_in_UK', models.NullBooleanField(default=False)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='arc_application.Application')),
            ],
            options={
                'db_table': 'PREVIOUS_REGISTRATION_DETAILS',
            },
        ),
        migrations.RemoveField(
            model_name='previousname',
            name='adult_id',
        ),
        migrations.RemoveField(
            model_name='previousname',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='adult_id',
        ),
        migrations.RemoveField(
            model_name='applicanthomeaddress',
            name='child_id',
        ),
        migrations.DeleteModel(
            name='PreviousName',
        ),
    ]
