# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-19 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_auto_20180216_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcreview',
            name='comments',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
