# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_previousaddress_previousname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousaddress',
            name='person_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('APPLICANT', 'APPLICANT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='previousname',
            name='other_person_type',
            field=models.CharField(blank=True, choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('APPLICANT', 'APPLICANT')], max_length=50),
        ),
    ]
