# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0003_auto_20180228_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='declaration_review',
        ),
    ]
