# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0003_arcreview_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcreview',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
