# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 17:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0004_remove_arc_declaration_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('audit_message', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'AUDIT_LOG',
            },
        ),
    ]
