# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0004_auto_20180430_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousregistrationdetails',
            name='five_years_in_UK',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='previousregistrationdetails',
            name='previous_registration',
            field=models.BooleanField(default=False),
        ),
    ]
