# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0005_auto_20180430_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousregistrationdetails',
            old_name='personal_detail_id',
            new_name='previous_registration_id',
        ),
    ]
