# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 17:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='audit_message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
