# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0006_auto_20180501_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousregistrationdetails',
            name='individual_id',
            field=models.IntegerField(default=0),
        ),
    ]
