# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0002_previousaddress_previousname'),
        ('arc_application', '0007_previousregistrationdetails_individual_id'),
    ]

    operations = [
    ]
