# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0003_auto_20180501_0950'),
        ('arc_application', '0008_merge_20180501_1913'),
    ]

    operations = [
    ]
