# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0009_merge_20180502_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousregistrationdetails',
            name='individual_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
