# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc_application', '0010_auto_20180502_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='comments',
        ),
    ]
